# This is the configuration file for fractal_sugar.
# Every field in this file is optional. A reasonable default value is used if a field is not present.

# Toggles whether to launch the application into fullscreen. Default is `false`.
launch_fullscreen = true

# The maximum particle speed. Default value is 7.0.
max_speed = 6

# The number of particles to simulate. Default value is 1_250_000.
particle_count = 2_500_000

# The diameter in pixels of each particle. Larger values may appear better on high resolution/DPI devices. Default is 2.0.
point_size = 2.5

# The spring coefficient `k` in Hooke's Law `F_s = -kx` used for particle spring-tension. Default value is 75.0.
spring_coefficient = 60

# The vertical field-of-view in degrees. Default value is 72.0.
vertical_fov = 75

# The scale factor to apply to the default. Default value is 1.0.
friction_scale = 1.8

# The decibel adjustment to apply to the incoming audio. Default value is -20.0.
audio_scale = -20

# This file can define a series of color schemes that may be applied to each particle.
# Each color scheme requires a title, 4 speed-dependent color values, and 4 index-dependent color values.
# The field [[color_schemes]] specifies that the following values define an object in the `color_schemes` list.
[[color_schemes]]
name = "Classic" # Defines the name for this color scheme. It is not used in code (atm...)
speed = [
    # Each of the lists below represents an RGB triplet plus a fourth speed value.
    # There must be **exactly 4** such lists below.
    # Each of the R, G, and B values must be in the range [0.0, 1.0] if not specified with a CSS color.
    # The speed value indicates the speed at which the color is most prominent. Values can be in range [0.0, 7.0]
    # Speed entries must be sorted by the speed value (last column) in ascending order.
    [0.0, 0.425, 0.55, 0.2],

    # All valid CSS notation is also permitted as RGB input! The speed value is still located in the last column of the list.
    ["#80B91A", 0.5],

    # Even the more exotic CSS color formats are available, as long as they are formatted correctly.
    ["hsl(277.65, 100%, 60%)", 3.5],

    # The speed value of the last entry is ommitted since this color will be most prominent at the maximum speed (7.0 units per second).
    [1.0, 0.4, 0.4],
]
index = [
    # Each of the lists below represents an RGB triplet plus a fourth index value.
    # There must be exactly 4 four such lists below.
    # All four values must be in the range [0.0, 1.0].
    # The index value indicates where in the jello-grid this color is most prominent.
    # Index entries must be sorted by the index value (last column) in ascending order.
    [0.6, 0.4, 0.25, 0.25],
    [0.3, 0.25, 0.6, 0.5],
    [0.6, 0.4, 0.5, 0.75],
    "#94159d", # The index value of the last entry is ommitted since this color will be most prominent at the maximum speed. Thus, it is valid to provide only a CSS color.
]

[[color_schemes]]
name = "Northern Lights"
speed = [
    [0.04, 0.5, 0.35, 0.2],
    [0.55, 0.2, 0.45, 0.8],
    [0.85, 0.45, 0.02, 1.5],
    [0.65, 0.08, 0.04],
]
index = [
    [0.0, 0.25, 0.45, 0.25],
    [0.08, 0.5, 0.35, 0.5],
    [0.0, 0.25, 0.35, 0.75],
    [0.0, 0.5, 0.35],
]

[[color_schemes]]
name = "Arctic"
speed = [
    [0.15, 0.375, 0.42, 0.15],
    [0.55, 0.6, 0.65, 1.0],
    [0.75, 0.75, 0.8, 3.0],
    "GhostWhite", # Another example of CSS tom-foolery. https://www.w3schools.com/cssref/css_colors.asp
]
index = [
    [0.6, 0.65, 0.7, 0.25],
    [0.25, 0.3, 0.35, 0.5],
    [0.6, 0.6, 0.65, 0.75],
    [0.2, 0.25, 0.25],
]

[[color_schemes]]
name = "Magma Core"
speed = [
    [0.575, 0.01, 0.05, 0.18],
    [0.95, 0.72, 0.02, 1.2],
    [0.95, 0.62, 0.02, 3.5],
    [0.8, 0.65, 0.5],
]
index = [
    [0.4, 0.0, 0.04, 0.25],
    [0.2, 0.19, 0.16, 0.5],
    [0.35, 0.23, 0.06, 0.75],
    [0.22, 0.11, 0.08],
]

[[color_schemes]]
name = "Jungle"
speed = [
    [0.45, 0.3, 0.2, 0.15],
    [0.7, 0.7, 0.05, 0.5],
    [0.05, 0.8, 0.25, 2.0],
    [0.2, 0.95, 0.3],
]
index = [
    [0.65, 0.4, 0.1, 0.25],
    [0.0, 0.4, 0.2, 0.5],
    [0.5, 0.4, 0.0, 0.75],
    [0.0, 0.5, 0.15],
]

[[color_schemes]]
name = "Black & Yellow"
speed = [
    [0.45, 0.4, 0.0, 0.16],
    [0.65, 0.55, 0.1, 0.5],
    [0.8, 0.75, 0.65, 3.0],
    "WhiteSmoke",
]
index = [
    [0.15, 0.18, 0.15, 0.25],
    [0.5, 0.45, 0.0, 0.5],
    [0.18, 0.15, 0.18, 0.75],
    [0.5, 0.45, 0.0],
]