[package]
name = "fractal_sugar"
version = "0.1.2"
authors = ["Ryan Andersen <ryco117@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021" # Rust Edition used in this package

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.9.1"
cpal = "0.14.0"
crossbeam-channel = "0.5"
css-color-parser = "0.1.2"
png = "0.17.6"
rustfft = "6.0.1"
serde = { version = "1.0.143", features = ["derive"] }
toml = "0.5.9"
vulkano = "0.30.0"
vulkano-shaders = "0.30.0"
vulkano-win = "0.30.0"
winit = "0.26.1"

[dependencies.windows]
version = "0.40.0"
features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_UI_WindowsAndMessaging",
]

[[bin]]
name = "fractal_sugar"
path = "src/main.rs"
