[package]
name = "fractal_sugar"
version = "0.1.3"
authors = ["Ryan Andersen <ryco117@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021" # Rust Edition used in this package
build = "build.rs"

[build-dependencies]
embed-resource = "1.7.3"

[dependencies]
anyhow = "1.0.65"
bytemuck = "1.9.1"
cpal = "0.14.0"
crossbeam-channel = "0.5"
css-color-parser = "0.1.2"
egui = "0.19.0"
egui_winit_vulkano = "0.20.0"
ico = "0.1.0"
rustfft = "6.0.1"
serde = { version = "1.0.143", features = ["derive"] }
toml = "0.5.8"
vulkano = "0.31.0"
vulkano-shaders = "0.31.0"
vulkano-win = "0.31.0"
winit = "0.27.3"

[dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_UI_WindowsAndMessaging",
]

[profile.release]
lto = true
strip = true

[[bin]]
name = "fractal_sugar"
path = "src/main.rs"
