[package]
name = "rust_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.9.1"
cpal = "0.13.5"
kernel32-sys = "0.2.2"
rustfft = "6.0.1"
user32-sys = "0.2.0"
vulkano = "0.29.0"
vulkano-shaders = "0.29.0"
vulkano-win = "0.29.0"
winapi = "0.3.9"
winit = "0.26.1"

[[bin]]
name = "rust_playground"
path = "src/main.rs"
