[package]
name = "fractal_sugar"
version = "0.1.0"
authors = ["Ryan Andersen <ryco117@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021" # Rust Edition used in this package

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.9.1"
cpal = "0.14.0"
css-color-parser = "0.1.2"
kernel32-sys = "0.2.2"
rustfft = "6.0.1"
serde = { version = "1.0.143", features = ["derive"] }
toml = "0.5.9"
user32-sys = "0.2.0"
vulkano = "0.30.0"
vulkano-shaders = "0.30.0"
vulkano-win = "0.30.0"
winapi = "0.3.9"
winit = "0.26.1"

[[bin]]
name = "fractal_sugar"
path = "src/main.rs"
